services:
  postgres:
    image: postgres:15
    container_name: dotnet-job-runner-postgres
    environment:
      POSTGRES_USER: dotnet
      POSTGRES_PASSWORD: dotnet
      POSTGRES_DB: dotnet_job_runner
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
